### ISSUE TITLE
Don't show moves for eggs

### ISSUE THREAD

**Issue by devNoiseConsulting** [RealDeviceMap/RealDeviceMap#10]
![screen shot 2019-01-16 at 12 08 44 pm](https://user-images.githubusercontent.com/1700471/51265776-8427f000-1987-11e9-90f6-ffa3959715a2.png)

On my map I see the moveset listed when the raid is just an egg. 

Should the raid_pokemon_move_1 and raid_pokemon_move_2 be set to null when saving a new egg to the db?

**Comment by 123FLO321** [comment]
What frontend is that?

**Comment by devNoiseConsulting** [comment]
I am using the RDM docker frontend.

**Comment by 123FLO321** [comment]
Ah!
I see. This is already fixed on the beta. 

Will close this once the beta is merged.

**Comment by devNoiseConsulting** [comment]
cool. thanks
