### ISSUE TITLE
[Frontend Bug Report] Inaccurate Dashboard Account Stats since PR83 (and before)

### ISSUE THREAD

**Issue by kbtbc** [RealDeviceMap/RealDeviceMap#116]
**Describe the bug**
Dashboard does not reflect the true status of accounts. 

**To Reproduce**
1. Go to Dashboard
2. Click on Accounts
3. Scroll down to view your account status.
4. Cross reference with database queries to see numbers that don't match, and stats that aren't useful.

**Expected behavior**
A clear, accurate description of account statistics, including good, warned, banned (and suspended would be nice). 

- Stats should accurately reflect the true account status.
- 'Other' column has never served any purpose, should be removed or have reason.
- 'Banned' column should be split up into 'permban' and '30day ban' (suspended).
- Accounts should not be good & shadowbanned at the same time.
- Warned accounts that have passed warning expired date should be (optionally) set to good.

**System**
 - Running in docker: yes
 - RDM Version: PR#83

**Additional context**
As per issues discussed in Discord related to expired warnings, suspensions, and other incorrect Dashboard account stats.

**Comment by Fabio1988** [comment]
is this a thing yet? or old behavior? @123FLO321

**Comment by Fabio1988** [comment]
implemented by #432 

if anything is missing, pls reopen
