### ISSUE TITLE
[Backend Bug Report] Smart Raid Instance Doesn't update neighboring gyms if scan failed.

### ISSUE THREAD

**Issue by kbtbc** [RealDeviceMap/RealDeviceMap#117]
**Describe the bug**
Using a smart raid instance, if a scan fails in a scan location where there are multiple gyms, and one gym has an egg active, Smart Raid will fail to return to update the other gyms. 

Issue has been discussed in detail on Discord.  Posting here so it doesn't get forgotten.

**Comment by Fabio1988** [comment]
is this related to the described issue https://github.com/RealDeviceMap/RealDeviceMap/issues/172 ?

**Comment by Fabio1988** [comment]
fort logic reworked in #394 . if this is still a topic after merge, pls reopen.
