### ISSUE TITLE
GetPlayer

### ISSUE THREAD

**Issue by unseenmagik** [RealDeviceMap/RealDeviceMap#126]
**Is your feature request related to a problem? Please describe.**
Is there a way to add in `GetPlayer` response in RDM so the details for trainerName, Level etc can be sent via web hook

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 123FLO321** [comment]
trainer name and level already get sent via webhook

**Comment by unseenmagik** [comment]
> trainer name and level already get sent via webhook

Only if the account manager or accounts are used from the DB.
If using GDS and you do not use accounts from the database (manual account assignment to the device via manual login of PTC) these details are not sent in the web hook.

**Comment by Fabio1988** [comment]
if RDM does not manage the accounts, why should it send webhook?

If this is really needed then feel free to open the issue again, I will close it for now, seems to have no high prio, old issue.
