### ISSUE TITLE
[Feature Request] Distinguish betwenn banned and suspended

### ISSUE THREAD

**Issue by VampireSilence** [RealDeviceMap/RealDeviceMap#127]
**Is your feature request related to a problem? Please describe.**
Correctly distinguish between "banned" und "suspended" (for 30 days) accounts, when detecting a punishment.

**Describe the solution you'd like**
Pixel check for "30" in "..you are suspended/banned.."-screen.

**Describe alternatives you've considered**
Get it via proto, if there is one.

**Additional context**
We could then use suspended accounts again after 30 days, without having to check thousands of permabanned accounts as well.

**Comment by whitewillem** [comment]
There is already a account_suspended action. Gds/gc just have to start using it

**Comment by whitewillem** [comment]
GDS has implemented it in the last release. Don't know about GC but i think this issue should be closed now.

**Comment by 123FLO321** [comment]
Implemented in #83
