### ISSUE TITLE
[Backend Bug Report] Deleting device from leveling instance not working

### ISSUE THREAD

**Issue by n0varino** [RealDeviceMap/RealDeviceMap#128]
**Describe the bug**
When a device gets removed, new leveling instance seems to have problems.
I had two devices on a dedicated leveling RDM docker instance, and removed one of them (deleted the device from the database through phpmyadmin since RDM doesnt have a clean way to delete devices).
The "instances" page still shows two accounts being used, and it doesnt spin any stops.
XP/hour are at 0%.

**To Reproduce**
1. Create dedicated RDM docker instance for leveling
2. Assign two devices to leveling instance.
3. Remove one of them (delete device from database)
4. Check instance page.

**Comment by 123FLO321** [comment]
You can only clear devices from the database while RDM is stopped.
Removing it "hot" will cause unexpected problems
