### ISSUE TITLE
[Feature Request] Make Using Warned Accounts Optional.

### ISSUE THREAD

**Issue by kbtbc** [RealDeviceMap/RealDeviceMap#132]
**Is your feature request related to a problem? Please describe.**
Currently, forcing RDM to use warned accounts breaks quest instances due to a mitm provider issue.  But beyond that, it is also a preference of several mappers to only use good/clean accounts.

**Describe the solution you'd like**
A checkbox in the dashboard that would tell RDM to only use accounts in a good state, making it optional to use or not use warned accounts.

**Comment by ttanguay** [comment]
Would also like this feature optional. I want to reuse warned accounts eventually, but would rather manage it myself and use fresh accounts that are going to be warned within 4-7 days of leveling regardless (pre flagged and going to be warned anyway so use them while i can).

**Comment by HTPaddy** [comment]
Yes, please make this optional. I’m not interested in using warned accounts for questing

**Comment by svenberg** [comment]
Bumping this one

**Comment by Fabio1988** [comment]
https://github.com/RealDeviceMap/RealDeviceMap/pull/204 merged in this PR
