### ISSUE TITLE
[Feature Request] Chained auto assignments on complete & date/time assignments for events

### ISSUE THREAD

**Issue by jepke** [RealDeviceMap/RealDeviceMap#135]
**Describe the solution you'd like**
Currently we can have multiple fixed time assignments but only 1 oncomplete.
Example: I have 1 area i want to scan for quests 100% but i do have about 4 hours left untill 8am in the morning. I want to utilize those 4 hours to get some extra quests scanned. I can use a on complete to go to the secondary quest instance but that one only takes 2 hours so still 2 left. The time the second one finishes varies everyday so to make the most of every minute i would like to chain up multiple oncomplete triggers.

So if we can give a priority number to each on complete. If priority 1 is complete do 2 if 2 complete 3 and so on.

For date/time assignments this comes in place for events like community day or other specific events that are worth changing focus on what is scanned at that time.

**Comment by nileplumb** [comment]
I'd quite like to try chaining smaller quest instances to try and combat the poor route choices rdm is making of my all in one quest instance ( creating large jumps and causing logout loops)

Again having a chain eg quest1->quest2->.....quest8->Pokémon scan would help
