### ISSUE TITLE
[Frontend Bug Report] Account page

### ISSUE THREAD

**Issue by whitewillem** [RealDeviceMap/RealDeviceMap#139]
**Describe the bug**
Account page is a mess.

**To Reproduce**
1. Go to https://website.com/dashboard/accounts
2. Open eyes.

**Expected behavior**
1. Cooldown column should go as it depends on where and how you would want to use it.
2. 'banned' column should be split up into 'permban' and '30day ban'
3. accounts should not be good & shadowbanned at the same time.

**Comment by 123FLO321** [comment]
duplicate of #116
