### ISSUE TITLE
[Backend Bug Report] RDM to flood itself with device requests when iphones are sitting on a complete quest instance.

### ISSUE THREAD

**Issue by jepke** [RealDeviceMap/RealDeviceMap#142]
**Describe the bug**
When iphones are sitting on a complete quests instance something triggers a shit ton of requests and calculations causing RDM to flood and kill itself.

**To Reproduce**
Put a few iphones on a quest instance that is 100% complete

**Expected behavior**
When a quest instance is complete it doesn't have to do any calculations just send a "pause" the the device. Would be fancy if we could make it go to the next instance. As asked in #135 

**Screenshots**

**System**
 - Running in docker: yes
 - Docker Engine Version: latest
 - Host OS: debian 10 
 - RDM Version latest

**Comment by whitewillem** [comment]
Idk if its the calculations rdm keeps doing or the extreme amounts of requests for a job from gds but its definitly a issue. This even triggered cloudflare to mark traffic as ddos. G is looking into it tho. But there are resources available when this happens and that makes it a bit weird

**Comment by 123FLO321** [comment]
Fixed in #141

**Comment by Fabio1988** [comment]
if fixxed, should be closed for a clear overview?! or does it still happen?
