### ISSUE TITLE
[Backend Bug Report] Weather condition not updated

### ISSUE THREAD

**Issue by svenberg** [RealDeviceMap/RealDeviceMap#148]
**Describe the bug**
Weather condition is not updated.

**To Reproduce**
1. Check an existing cell's weather
2. Go there, scan weather
3. It does not get updated

**Expected behavior**
Weather condition to be updated

**Screenshots**
None, but can arrange if needed

**System**
 - Running in docker: yes
 - Docker Engine Version: unknown
 - Host OS: ubuntu 18
 - RDM Version master, as of 2020-07-07

**Additional context**
None

**Comment by svenberg** [comment]
![image](https://user-images.githubusercontent.com/46693744/86828543-ae95cd80-c093-11ea-970f-c409ff6ae51e.png)

**Comment by Pogodenhelder** [comment]
i can confirm that its always windy while in game its totally different.
![Schermafbeelding 2020-07-07 om 21 20 37](https://user-images.githubusercontent.com/35499601/86831865-bd7e7f00-c097-11ea-9619-115828d281f8.png)

**Comment by 123FLO321** [comment]
Introduced in #113
