### ISSUE TITLE
[Feature Request] Add Device Groups to Auto-Assignments

### ISSUE THREAD

**Issue by bushe** [RealDeviceMap/RealDeviceMap#151]
**Is your feature request related to a problem? Please describe.**
Add Device Groups to Auto Assignments for easier management of device assignments

**Describe the solution you'd like**
In the drop down for "Select Target Device" it should show two groups, one for groups and one for devices ex:

[Device Groups]
- All Devices
- Group 1

[Devices]
- Device 1
- Device 2
- Device 3

Optionally might want to add a delay field to provide a small delay in assigning the instances when a group is selected to not have all devices logout/in right away

**Describe alternatives you've considered**
Optionally or Additionally Assign Devices could be added to Instance pages to allow multi selecting devices to assign to an instance

**Additional context**
Just some thoughts to simplify management of devices

**Comment by 123FLO321** [comment]
I am already working on this (+chained assignments).
Screenshot of local dev build:
![image](https://user-images.githubusercontent.com/1949038/87861441-91d88000-c946-11ea-9472-7bdecdc82f51.png)

**Comment by bushe** [comment]
Looks awesome! Was just putting this here for tracking but appreciate the fast work on this!
