### ISSUE TITLE
[Feature Request] Gym name scanning

### ISSUE THREAD

**Issue by Fabio1988** [RealDeviceMap/RealDeviceMap#163]
**Is your feature request related to a problem? Please describe.**
Actually newly created gyms are stored as "Unknown Gym Name", because gym name will only be send when gym is clicked, nearby is not enough (in nearby only position and picture will be send).

**Describe the solution you'd like**
A better solution would be: If a new gym is in nearby the worker should click once on the gym, it's not much time killed for that, because gym click should not count towards cooldown. The new gym is actually added into RDM immediately without gym name, in the same moment the gym could be clicked and all data are right for insert, only check if gym-id is existing already before, if not click on gym.

**Describe alternatives you've considered**
At second it would be possible to track gym name changes (not from "Unknown" or NULL) within Auto-Quest Instance. All stops have to be clicked to receive Quest-Information. Click on all Gyms nearby to receive names and write changes to DB wouldn't affect cooldown. This would not be much effort in parallel to quests.

**Additional context**
So 1 Feature Request with 2 solutions to scan gym names. If this 2 things are too much database-query-load then it would also be possible to create a gym interface in RDM, where only the Name can be edited, Picture, Location and ID should not be editable, because worker are working with it.

**Comment by JoniValles** [comment]
This is not related to RDM. You should ask it to your mitm provider. 
Anyway you can use [Ingress-Scrapper](https://github.com/ClarkyKent/ingress_scraper) to get your missing gym/pokestop names.

**Comment by Fabio1988** [comment]
ok thx, then I have to ask the mitm provider, thanks.
