### ISSUE TITLE
[Feature Request] Extend functionality "Clear All Quests" in Utilities

### ISSUE THREAD

**Issue by Fabio1988** [RealDeviceMap/RealDeviceMap#181]
**Is your feature request related to a problem? Please describe.**
"Clear All Quests" functionality in Utilities is not executable. Received Proxy-Error after some time, maybe timeout. I think the command is overloading the DB also. Some seconds/minutes after error all quests on stops were removed in UI, so it happened after timeout.

**Describe the solution you'd like**
Is it possible to extend the "Clear All Quests" functionality in Utilities? Maybe a list of all quest instances, so I can delete not "ALL" but "SOME" quests regarding to the instance. Maybe this will resolve the issue.

e.g. Event switch at 3am.... I started scanning at 1am... So I want to delete all instances, which have finished before 3am.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Gladiator10864** [comment]
You can already clear just individual instances. Go to Instances > Edit instance > Clear Quests, this will only clear quests within that geofence. With 6k Pokestops, I can't say I've ever had the "Clear All Quests" function completely fail though.

**Comment by Fabio1988** [comment]
Yeah I saw actually that the code have this functionality.. but didn't find it where, thanks for the hint.
