### ISSUE TITLE
[Feature Request] Circle Split Pokemon Instance

### ISSUE THREAD

**Issue by JoniValles** [RealDeviceMap/RealDeviceMap#183]
It's known that adding devices to a circle pokemon instance is not improving it directly proportional.

8 devices on 1 instance = 645s 
8 devices on 8 instances ~= 524s

Creating one instance that splits X coords per device, where X* could be added by user, should fix this problem. 
*Another option X = coords/devices.

e.g: 
500 coords 
9 devices 

User wants 60 coords per device. 

1/500 to 60/500 for 1st device.
61/500 to 121/500 for 2nd device.
...

So avoiding long jumps, pokemon instances would improve round times. Obviously instances needs to be sorted first.

**Comment by Dewpg** [comment]
That wouldnt minimize longs jumps.  It should do a calculation based on devices assigned, to produce X number of shorter optomized routes.  It wouldnt optimize it to just pull 1-60 and 61-120.  It would possibly create More long jumps if it does that.

**Comment by Fabio1988** [comment]
should be done in #204  ? :)
