### ISSUE TITLE
[Backend Bug Report] Pvp Ranking shows impossible evolutions

### ISSUE THREAD

**Issue by nappa85** [RealDeviceMap/RealDeviceMap#191]
**Describe the bug**
On WebHooks, inside pvp_rankings_great_league and pvp_rankings_ultra_league, sometime are listed impossible evolutions, like Vespiqueen for a male Combee.

**To Reproduce**
1. Enable WebHooks
2. Check a male Combee WebHook

**Expected behavior**
Male Combee can't evolve in Vespiqueen

**System**
 - Running in docker: yes
 - Docker Engine Version: 18.09.7
 - Host OS: Ubuntu 16.04.6
 - RDM Version 1.22.2 (032a18db4c30a866f823264a357d7f214ec393c9)

**Comment by Fabio1988** [comment]
Fixed in RDM Version: 1.27.1 #216
