### ISSUE TITLE
[Backend Bug Report] Om nom nom I love RAM

### ISSUE THREAD

**Issue by nicholaspearson** [RealDeviceMap/RealDeviceMap#192]
**Describe the bug**
RDM eats memory, it never releases it!

**To Reproduce**
1. Run RDM for 7 days and monitor the container/process memory usage.

**Expected behavior**
The application is more memory efficient. 

**Screenshots**
![image](https://user-images.githubusercontent.com/9952461/105504936-3f469a80-5cc0-11eb-9003-3b6e8cde9ba6.png)

**System**
 - Running in docker: yes
 - Docker Engine Version: Docker version 20.10.2, build 2291f61
 - Host OS: CentOS 8.x
 - RDM Version: pr184

**Comment by 123FLO321** [comment]
please include the output of
`docker stats --no-stream realdevicemap`

Also are you using memory cache?
RDM is expected to use a lot of memory depending on the scanning sice with memory cache enabled (but should max out at something eventuelly).

**Comment by nicholaspearson** [comment]
```
[root@------- ~]# docker stats --no-stream rdm
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O     PIDS
58955710688f   rdm       8.41%     2.418GiB / 3.649GiB   66.27%    286GB / 166GB   42.8MB / 0B   67
```

We do buffer/cache yes, however, the buffers/cache is low.
```
             total        used        free      shared  buff/cache   available
Mem:           3736        2890         127         180         718         444
Swap:             0           0           0```

Oh, completely agree, however, we ensure data is truncated where appropriate, RDM should not be consuming more and more, graphs should show it peak and sit around that point unless more scanners are added and add to the RDM workload (which I would then expect more RAM consumption).

**Comment by Fabio1988** [comment]
Feel free to reopen. If database is configured right, this should not happen
