### ISSUE TITLE
[Backend Bug Report] Quests are finishing too early

### ISSUE THREAD

**Issue by kamieniarz** [RealDeviceMap/RealDeviceMap#200]
**Describe the bug**
Sometimes Quests are marked as `Completed` even if they have like 70% of all Quests done

**To Reproduce**
No idea how... It seems pretty random

**Expected behavior**
Finish when all Quests are scanned or when there were enough attempts in scanning some of them (eg if some pokestops are in database but they were removed from the game)

**Screenshots**
Don't have any atm but I'm pretty sure everyone knows what this issue is about. I can add some later in the comment section

**System**
 - Running in docker: yes
 - Docker Engine Version: 19.03.8
 - Host OS: Ubuntu 20.04.1 LTS
 - RDM Version: Pull Request #184 & 1.22.3

**Comment by kbtbc** [comment]
I also see this issue appear every now and then.   A Quest instance with many devices will falsely get marked as 'Completed', but only 70-80% are actually done.    It's random, but has happened more than 1/2 dozen times.   If I reassign devices back to the quest instance it will complete it.

**Comment by whitewillem** [comment]
RDM should try all stops 3 times and then mark as completed with current logic. Does it actualy mark it before that point?

**Comment by kamieniarz** [comment]
Looks like the issue is gone. The biggest and most known problem at the time was with finishing Quests at 70-90% (generally low values). Right now it can be very close to 100% but I belive it's related to retries so in fact RDM can't just try infinitely ;)
Closed
