### ISSUE TITLE
[Backend Bug Report] Quests are not finishing at all (stuck in a loop)

### ISSUE THREAD

**Issue by kamieniarz** [RealDeviceMap/RealDeviceMap#201]
**Describe the bug**
In the last days I've noticed some devices were stuck on Quest instances which were nearly finished. As an example status was updating from `Status: 4338|4338/4347 (99.8|99.8%)` to `Status: 4338|4347/4347 (99.8|100.0%)` and back to `Status: 4338|4338/4347 (99.8|99.8%)` and so on and so on. So in fact all devices were in loop for hours...

**To Reproduce**
No idea tbh. It's proly connected to deleted Pokestops which couldn't be processed

**Expected behavior**
I think the best way to handle this situation would be a Quest scan retry - eg. if Quest couldn't be fetched in 3 attempts then leave it and try other ones and if all Quests are done but some of them were not completed in 3 attempts - mark that instance as done

**Screenshots**
Don't have any atm but I can provide it later

**System**
 - Running in docker: yes
 - Docker Engine Version: 19.03.8
 - Host OS: Ubuntu 20.04.1 LTS
 - RDM Version: Pull Request #184 & 1.22.3

**Comment by kbtbc** [comment]
I woke up this morning to a similar issue with the quest job.  It was at 99%, but ALL devices assigned (5 in total) to the job were all getting the "No username specified" warning in the RDM logs.   Auto-complete did not trigger, and the devices were stuck.   I did not notice the status changing from 99% to 100%, but wasn't looking carefully, so don't know for sure. 

![image](https://user-images.githubusercontent.com/7109934/111539075-db7ea200-8743-11eb-897b-d2790470f0b7.png)

**Comment by kamieniarz** [comment]
Looks like it's gone long time ago
