### ISSUE TITLE
[Backend Bug Report] Cell mon location does not get updated after being IVed

### ISSUE THREAD

**Issue by feigei** [RealDeviceMap/RealDeviceMap#222]
**Describe the bug**
When you get a cell mon that is updated later on, the location is still the cell location instead of the actual spawnpoint location. The grass icon overlay does get removed though.

**To Reproduce**
Not sure how to reproduce this issue as I only notice it if a member reports.

**Expected behavior**
The IVed mon location should be updated to the spawnpoint location.

**Screenshots**
In this case Maril is IVed, but is still in cell center instead of bottom right circle. Confirmed on a device and by member.
![maril](https://user-images.githubusercontent.com/43513167/122654238-5d6ad680-d14a-11eb-88f7-6d3eb8736f24.png)

**System**
 - Running in docker: yes
 - Docker Engine Version: 20.10.2
 - Host OS: Ubuntu 18.04 
 - RDM Version 1.29.1

**Additional context**
This has happened a few times already

**Comment by SkOODaT** [comment]
it is possible I effed up with the save stuff as I didn't really do anything with the save function... i figured it was updating correctly, im seeing a similar type issue in my database with my types stuff @123FLO321 can you take a look into it, the save function is a bit confusing

**Comment by feigei** [comment]
Fixed by #237
