### ISSUE TITLE
What's the suggested approach to pokemon table cleanup?

### ISSUE THREAD

**Issue by nappa85** [RealDeviceMap/RealDeviceMap#225]
If I didn't lost anything (and it could be), RDM hasn't any builtin system to cleanup pokemon table, that becomes bigger and bigger over time. The only tool I found is the "Truncate Pokemon Table" button inside Utilities, that can't be easily scheduled.
At the moment I've setup a cronjob that runs every minute and does brutally ```DELETE FROM pokemon WHERE expire_timestamp < UNIX_TIMESTAMP()```.
Is there any better way to keep the size of the table under control?
Thanks

**Comment by Fabio1988** [comment]
Did you try a procedure like that?

CREATE PROCEDURE `usp_pokemon_clear_old`()
BEGIN	
	DECLARE a, max_a INT DEFAULT 0;
	
	DROP TEMPORARY TABLE IF EXISTS p1;
	
	CREATE TEMPORARY TABLE p1
	SELECT
		ROW_NUMBER() OVER (ORDER BY id) row_num,
		id
	FROM
		pokemon
		
	WHERE
		expire_timestamp < UNIX_TIMESTAMP(NOW() - INTERVAL 1 HOUR);
	
	SELECT MAX(row_num) INTO max_a FROM p1;
	
	WHILE a < (max_a + 1000) DO
	   DELETE
			p
		FROM
			pokemon p
	      JOIN p1 ON p.id = p1.id
	  	WHERE
			p1.row_num BETWEEN a AND a+999;

	   SET a = a + 1000;
	END WHILE;
	
	SELECT max_a;
	
	DROP TEMPORARY TABLE IF EXISTS p1;
END
