### ISSUE TITLE
[Backend Bug Report] Insert fails on pokemon table because username column length is too short

### ISSUE THREAD

**Issue by cloud9team** [RealDeviceMap/RealDeviceMap#32]
**Describe the bug**
The column definition for username on rdmdb.pokemon is set to varchar(15). It is varchar(32) on every other table that has username. This allows you to import usernames longer than the max limit for rdmdb.pokemon. The insert fails silently when a username longer than varchar(15) is attempted to be inserted.  

**To Reproduce**
1. Import an account with a username longer than varchar(15) and less than varchar(32)
2. Login to account.
3. Watch it fail.
4. `docker logs realdevicemap --timestamps | grep "too long for"`` should pull up the error.
**Expected behavior**
Expected behavior: make me a warm meal after work, tell me you love me..wrong website.
Matching column definitions across all tables in a database would be a great place to start. 

**Screenshots**
N/A

**System**
 - Running in docker: [yes]
 - Docker Engine Version: [N/A]
 - Host OS: [N/A] 
 - RDM Version [highTable3000]

**Additional context**
If no "shiny stats" there would be no problem. 98% of the issues I see across almost every user trace back to rdm trying to be a one stop shop. In trying to do everything great, it kinda is starting to nothing well. My 2 cents and a nickel.

**Comment by 123FLO321** [comment]
I don't get how this is related to "shiny stats".
This is simply a wrong db structure that can be fixed easily.

**Comment by 123FLO321** [comment]
So you're basically saying that if we didn't continue developing RDM there would have been no bug.
Which is correct but is that the point of an project like that?

**Comment by TRGoCPftF** [comment]
That wasn’t the point of the message from what I read. The issue here is that the DB schema was merged before being validated for column entries referencing the same data, and thus have mismatched data types resulting in this bug

**Comment by whitewillem** [comment]
Since its a pr now anyway... i would like to ask you to reconsider if having username in pokemon table is a smart thing. Its getting abused a lot. (Read: you can catch and sell shiny with this setup)

**Comment by ttanguay** [comment]
The intent of username in Pokémon table was for shadowban detection.

**Comment by cloud9team** [comment]
Running these changes locally from the moment this bug was found. Have not had an issue now that this column matches the length of allowed imports. This should be merged asap.
