### ISSUE TITLE
Non-matching webhook property nomenclature

### ISSUE THREAD

**Issue by versx** [RealDeviceMap/RealDeviceMap#330]
All other webook properties are snake cased while `baseHeight` and `baseWeight` are camel cased.
https://github.com/RealDeviceMap/RealDeviceMap/blob/85b938f691f97e829b22b0680e484ff4b451e811/Sources/RealDeviceMapLib/Modell/Pokemon.swift#L56
https://github.com/RealDeviceMap/RealDeviceMap/blob/85b938f691f97e829b22b0680e484ff4b451e811/Sources/RealDeviceMapLib/Modell/Pokemon.swift#L57

**Comment by Fabio1988** [comment]
You are right, renaming or would it make more sense to remove it?
