### ISSUE TITLE
[Backend Bug Report] Follow up to issue 33 - out of range value for column shiny

### ISSUE THREAD

**Issue by cloud9team** [RealDeviceMap/RealDeviceMap#34]
**Describe the bug**
Insert fails somewhere that has column shiny. 
`Failed to execute query. (Out of range value for column 'shiny' at row 1\r\n","stream":"stdout","time":"2020-02-06T14:06:35.091622027Z"}`
This is a brand new stock database created lastnight, with fix for issue 33. 
**To Reproduce**
1. No clue but...,
2. In terminal `docker container inspect realdevicemap`
3. Look for filename for "LogPath", Copy path and filename
4. `grep -wc "Out of range value for column 'shiny'" path/to/reallylongnamedfile.json` will give count of occurences
5. `grep -m 1 "Out of range value for column 'shiny'" path/to/reallylongnamedfile.json` prints date of first occurrence. 
6. Scratch head to find where this error originates.,,,

**Expected behavior**
Not to have data lost for arbitrary things like "isShiny".
 
**Screenshots**

**System**
 - Running in docker: [yes]
 - Docker Engine Version: [if applicable, e.g. 19.0]
 - Host OS: [e.g. Ubuntu 18.04] 
 - RDM Version [current]

**Additional context**
My comments yesterday were in reference to things like this. Development is not necessarily adding features, it is also resolving issues and verifying that there are no current issues. In that process when an issue is identified, most of the time it's necessary to stop and ask a couple questions. 
1. Is this a necessary feature?
2. If yes, stop adding new content until any and all conflicts are resolved. Otherwise we are just pouring gas on a fire.
3. If no, remove it.
Currently, from what I see, we are in pour gas on fire mode.
just doing a grep count for the occurrence of "ERR" (error) on a log file from a container created 6 hours ago, 100% stock returns a count of 431,931. That is somewhat unsettling.

**Comment by whitewillem** [comment]
I did not find where it happens yet. But RDM is inserting weird values in shiny column. Apparently some to big for the column resulting in your error.

**Comment by cloud9team** [comment]
The issue is happening somewhere in the pokemon table. The error logs don't provide much information as to which query it is. After running a few queries, i noticed that the values in the shiny column were never 3 digits (it's pretty clear it is saving poke id in some cases). I changed the column value from tinyint(1) to smallint (tiny int doesn't cover all possible ids). I haven't had an out of range error since changing that column (which also seemed to be causing table deadlock). I also now have 3 digit ids in that column. If it is purposely saving poke id and not just 0 or 1, I'd suggest the column definition be changed. 
Current values when running select distinct shiny > `0 , NULL , 13  ,1, 316, 48, 167`

**Comment by whitewillem** [comment]
No it should only be 0 or 1. Something going wrong with a few spawns. I have 5 out of 187k with weird values in pokemon.shiny and its not the pokemon id.

**Comment by 123FLO321** [comment]
Should be fixed in #39. But not tested yet.
