### ISSUE TITLE
[Frontend Bug Report] Incorrectly formatted width of the Invasion filter.

### ISSUE THREAD

**Issue by Deses** [RealDeviceMap/RealDeviceMap#350]
**Describe the bug**
The table header for the Rocket invasions is not properly displayed, every other filter displays correctly.

![image](https://user-images.githubusercontent.com/1654959/167978590-672bc004-dfb7-4b44-912c-d7ac6d69934c.png)

It's not something about my ongoing spanish translation, in the unmodified development branch it also happens:

![image](https://user-images.githubusercontent.com/1654959/167978950-3878ee03-2723-40df-bb15-bb881d53430f.png)

**To Reproduce**
1. Go to 'Invasion filers'
2. See error

**Expected behavior**
Properly sized table header.

![image](https://user-images.githubusercontent.com/1654959/167978986-ee22d11e-5e43-4107-939c-9a133ce1c686.png)

**System**
 - Running in docker: [yes]
 - Docker Engine Version: [if applicable, e.g. 19.0]
 - Host OS: [Mint] 
 - RDM Version [f5a98ec1fc3d122143a563ec10ac632852669dea]

**Client**
 - OS: [Windows 10]
 - Browser [Chrome]

**Comment by Fabio1988** [comment]
fixed in #353
