### ISSUE TITLE
[Feature Request] EX tags/passes

### ISSUE THREAD

**Issue by whitewillem** [RealDeviceMap/RealDeviceMap#36]
**Is your feature request related to a problem? Please describe.**
When ex passes go out niantic removes ex tags. RDM pick this up and updates database as if its not a ex gym at all.

**Describe the solution you'd like**
If possible: 2 columns. 1 that always tells if its a ex gym, the other to show if passes are send out or not.

**Comment by 123FLO321** [comment]
How long do these XP passes usually get blocked for?

**Comment by Fabio1988** [comment]
Normally ex passes block 9-10 days. But ex raid gym will remain ex raid gym. Maybe remove tag only after 2 weeks?

Also the possibility to show either exraid passes are out or not would be fency.

**Comment by Fabio1988** [comment]
actually we don't know much about ex-passes... if this topic comes up again, then we can modify RDM to respect the tag. But maybe Niantic did change that behavior, actually there are not EX-Passes since 2 years.
