### ISSUE TITLE
[Frontend Bug Report] RDM crashes after logging into the UI

### ISSUE THREAD

**Issue by rexbutz** [RealDeviceMap/RealDeviceMap#38]
**Describe the bug**
Built RDM in Ubuntu 18.04 without docker.  Pointed to external mysql db.  Start rdm and everything rungs great.
As soon as I goto the UI (http://localhost:9000), login and try to go to any other page (devices, accounts, instances, settings, etc...), rdm crashes with the following error:

Could not cast value of type 'RealDeviceMap.Pokemon' (0x55f3f9f53510) to 'Foundation.NSObject' (0x7f32a2e89a30).

Using swift 4.1 with swiftenv per readthedocs instructions.

**To Reproduce**
1. Start RDM
2. Goto http://localhost:9000
3. Login
4. Try to navigate to any other page
5. RDM crashes with:
"Could not cast value of type 'RealDeviceMap.Pokemon' (0x55f3f9f53510) to 'Foundation.NSObject' (0x7f32a2e89a30)."

**Expected behavior**
Expect to be able to navigate through UI menus.

**Screenshots**

**System**
 - Running in docker: no
 - Docker Engine Version: not applicable
 - Host OS: Ubuntu 18.04
 - RDM Version:  Master branch

**Client**
 - OS: Any
 - Browser Any

**Additional context**
Swift 4.1 via swiftenv

**Comment by 123FLO321** [comment]
What line does that crash at?
can you attach the symbolicated crash report?

**Comment by rexbutz** [comment]
I was finally able to stand up a independent instance to test without crashing my production environment.  I have isolated the crash to when it goes from the map view to any of the menu items.  

If I authenticate and goto the map, click a menu item, it crashes... I restart rdm then just refresh the browser with the "https://localhost:9000/dahsboard/settings (or whichever)" and all the menu items works just fine.

If I go back to the map and try to get back in to a menu item it crashes again.

How do I tell which line it crashes at and where do I find the symbolicated crash report?

**Comment by rexbutz** [comment]
More information:  If I use the filter to hide everything on map view, it will not crash and I can switch between map view and menu items without issue.   As soon as I switch something from hide to show, it will crash.

Looks like it might be an image issue... for non-docker, where should the images be?

**Comment by 123FLO321** [comment]
@rexbutz did you get this working using the new instructions in the wiki?

**Comment by rexbutz** [comment]
Rebuilt from scratch and it's running rock solid now.  I will close, thanks!
