### ISSUE TITLE
Scan-Next mode of use

### ISSUE THREAD

**Issue by jack1230** [RealDeviceMap/RealDeviceMap#382]
I have been reading about this information.
https://github.com/RealDeviceMap/RealDeviceMap/wiki/7.-API-Calls

I have tried to use this in post but it shows me error 406:
api/set_data?scan_next=true&instance=${name}&coords='[{"lat":46.87287,"lon":22.30138}]'

As a suggestion, it would be more recommended that coords be sent in body so that it can be processed and there is no conflict or which one would be recommended, I use axios for nodejs.

This api works for me:
api/get_data?scan_next=true&queue_size=true&instance=${name}

Thank you

**Comment by Fabio1988** [comment]
406 is something else, are you authenticated? Is the coords json encoded?

**Comment by jack1230** [comment]
I use this basic example.

const axios = require('axios').default; //npm i axios

var fromData = `scan_next=true&instance=${MyDevice}&coords='[{"lat":46.87287,"lon":22.30138}]'`

axios({
  method: 'post',
  url: 'http://Ip:Port/api/set_data',
  data: fromData,
  headers: {
    "Content-Type": 'multipart/form-data'
  },
  auth: {
    username: '${MyUser}',
    password: '${MyPass}',
  }
}).then(function (response) {
  console.log(response.status);
})
.catch(function (error) {
  console.log(error);
});

**Comment by 123FLO321** [comment]
this is a working axios example:

```ts
async function  scanAtCoords(url: string, username: string, password: string, instance: string, coords: {lat: number, lon: number}[]): Promise<void > {
    const request = await axios.request({
        url: url,
        method: "GET",
        auth: {
            username: username,
            password: password
        },
        params: {
            instance: instance,
            coords: JSON.stringify(coords),
            scan_next: true
        },
    })
}
```
