### ISSUE TITLE
[Feature Request] Clear Pokemon in RDM itself

### ISSUE THREAD

**Issue by Fabio1988** [RealDeviceMap/RealDeviceMap#404]
1. Define interval/expired period in config
2. MYSQL select IDs of expired mons (non-blocking query)
3. delete in multiple batches `where id = ?`

This won't block the table like event scheduling does 

```DELETE FROM pokemon WHERE expire_timestamp <= UNIX_TIMESTAMP() - 3600```

Handled in e.g. in a Pokemon thread to delete entries regularly

**Comment by jfberry** [comment]
You can do that delete statement with a LIMIT and just repeat it to get batches without selecting the ids - and check the rowcount to see when you are finished
selecting the ids (without a limit) could be a very bad idea; I'd suggest just doing the delete with a limit in a loop

**Comment by jfberry** [comment]
Default interval should be pretty often to try and restrict the size needed as well (delete limit will help if there is a backlog)
