### ISSUE TITLE
[Feature Request] Jump to nearby list

### ISSUE THREAD

**Issue by lenisko** [RealDeviceMap/RealDeviceMap#407]
**Is your feature request related to a problem? Please describe.**

Add a `Jump to nearby - Pokemon IDs` field to `Circle Pokemon, Circle Smart Pokemon` and maybe `Pokemon IV` instances which would auto jump to the area with nearby Pokemon from the list. This way we could instantly follow Unowns or other rare species.

**Describe the solution you'd like**
- New text field `Jump to nearby - Pokemon IDs` - to keep a list of Pokemons we would like to gather more info for
- `Jump to nearby limit (default 1)` - make x jumps and go back to original route, another jump would be possible from next point only (to prevent loops or overextending round time).

**Additional context**

Might be tricky to create connection between nearby and iv pokemon?

**Comment by Fabio1988** [comment]
implemented a approach in #409 to support nearby cell mons

I think it's only worth to do in a IV instance... would not know how to use that with pokemon circle.

if that does not work as you wish pls reopen issue and discuss it :)
