### ISSUE TITLE
[Feature Request] Add a file to migrations to re-create a fresh database database

### ISSUE THREAD

**Issue by cloud9team** [RealDeviceMap/RealDeviceMap#43]
**Is your feature request related to a problem? Please describe.**
Rdm instance is fine. database is corrupt. Wanting to start with a completely fresh database means a complete re-install of rdm. 
**Describe the solution you'd like**
A method to recreate the database structure.
**Describe alternatives you've considered**
just creating the table myself as described here
https://github.com/RealDeviceMap/RealDeviceMap/blob/4a051194f6c1b3b09911d7e2c89542a2736e0fa0/Sources/RealDeviceMap/Controller/DBController.swift#L184
**Additional context**

**Comment by 123FLO321** [comment]
If you just let rdm start (with a new db) it will create the db but not do anything else as long as you don’t add devices/etc.

**Comment by Fabio1988** [comment]
RDM does execute all the migrations itself with a new DB. so clean your DB or choose a different one. There is no need for a separate full migration sql file :) 

https://github.com/RealDeviceMap/RealDeviceMap/tree/master/resources/migrations
