### ISSUE TITLE
LevelUp Not updating spins

### ISSUE THREAD

**Issue by BadWolf0081** [RealDeviceMap/RealDeviceMap#469]
LevelUp  Mode is Not updating the spins column of the account table

**To Reproduce**
1. Run Level Up mode
2. check account spins before and after
3. No Change

**Expected behavior**
This column should update with each spin on levelup

**Comment by VampireSilence** [comment]
I can confirm that.

**Comment by Pogodenhelder** [comment]
confirmed ^^

**Comment by Fabio1988** [comment]
Mostly because leveling does not store any data.  I can check that... Maybe it's possible somehow
