### ISSUE TITLE
[Feature Request] Use bbox for quest clearing of instance

### ISSUE THREAD

**Issue by Fabio1988** [RealDeviceMap/RealDeviceMap#472]
combine the expensive sql query for ST_GEOMFROMTEXT with a bbox to filter the stops in 2 steps.

first create bbox out of the geofence coordinates and use that in sql query too

```sql
SELECT * FROM pokestop WHERE (lon BETWEEN bbox.minLon AND bbox.maxLon) AND (lat BETWEEN bbox.minLat AND bbox.maxLat) AND (ST_CONTAINS(....))
```
Ref:
https://github.com/TurtIeSocks/Koji/blob/main/server/model/src/utils/mod.rs#L22
https://github.com/TurtIeSocks/Koji/blob/main/server/model/src/api/single_vec.rs#L21

**Comment by VampireSilence** [comment]
Missing 1 "bbox." before "maxLat". Has to be:

SELECT * FROM `pokestop` WHERE (`lon` BETWEEN bbox.minLon AND bbox.maxLon) AND (`lat` BETWEEN bbox.minLat AND bbox.maxLat) AND (ST_CONTAINS(....))
