### ISSUE TITLE
Use least used account instead of recently used

### ISSUE THREAD

**Issue by Fabio1988** [RealDeviceMap/RealDeviceMap#527]
https://github.com/RealDeviceMap/RealDeviceMap/blob/7ab2b8697e13f7aabf874d9c4c2e2e3face90273/Sources/RealDeviceMapLib/Modell/Account.swift#LL612C29-L612C29

Change sort to `ASC` for `last_used_timestamp` (configurable)

**Comment by Fabio1988** [comment]
@timxl73, why the downvote? It would be configurable globally :)

**Comment by TiMXL73** [comment]
Well, I don’t recall seeing the «`(configurable)`» part when I added my reaction but then again I also don’t remember what I ate for breakfast!

As long as current behavior can be kept, it’s all good. Reaction removed!
