### ISSUE TITLE
[Feature Request] quest_invasion image alternative

### ISSUE THREAD

**Issue by ttanguay** [RealDeviceMap/RealDeviceMap#54]
**Is your feature request related to a problem? Please describe.**
Generating >250K images taking >7 Gb is ugly and a headache for new server setup. Without enough horsepower this can crash a server -- happened to me on latest version on a linux vm.

**Describe the solution you'd like**
Implement an image overlay solution using existing images for quest_invasions.  Wasn't there one on gitlab before the move?

**Additional context**
Anything that could help the pain setting up new.  Copying from existing server works if both are local, but moving 7Gb remotely is not much better.

**Comment by SkOODaT** [comment]
https://gitlab.com/realdevicemap/RealDeviceMap-Beta/-/merge_requests/80

**Comment by 123FLO321** [comment]
On demand icon generating is planned

**Comment by Fabio1988** [comment]
#285
