### ISSUE TITLE
Quest Scan is not working with the latest RDM build.

### ISSUE THREAD

**Issue by Ou71and3r** [RealDeviceMap/RealDeviceMap#58]
Currently the latest RDM build is not working correctly with Ultra Quest. All devices are failing to scan due to wrong cooldown calculation.

**Comment by nileplumb** [comment]
Confirmed

**Comment by ch1zzu** [comment]
having similar issue with quest stuck on both Macless and UIC method. have to resort to downgrade to v1.5.0 to revert the changes on 1.6.x for the time being.

**Comment by whitewillem** [comment]
this made questing at least 10 times slower. fix pls

**Comment by imArize** [comment]
Experiencing the same. Had this since the leveling PR was first created.
