### ISSUE TITLE
[Backend Bug Report] Macless fails when no accounts under level 30

### ISSUE THREAD

**Issue by cloud9team** [RealDeviceMap/RealDeviceMap#65]
**Describe the bug**
When a device inits for first login, if no accounts less than tl 30, then rdm does not handle device.
**To Reproduce**
1. Have only level 30 in database
2. Start rdm
3. Watch all devices fail

**Expected behavior**
Device to init with assigned instance data reducing unecessary logins and eliminating this issue (bonus, solves 2 isssues)
Or 
Raise level defaults from 1-29 to 1-30 (and still have unecessary logins :/)
**Screenshots**

**System**
 - Running in docker: [yes|no]
 - Docker Engine Version: [if applicable, e.g. 19.0]
 - Host OS: [e.g. Ubuntu 18.04] 
 - RDM Version [e.g. 2.0.0]

**Additional context**

**Comment by whitewillem** [comment]
Its a known issue but still: can confirm and should be fixed if we can. Besides that it could break if you dont have low levels it also flags them.

**Comment by cloud9team** [comment]
@whitewillem 
> Besides that it could break if you dont have low levels it also flags them.
It will flag the 30s in db? Because I just discovered I have a 96% false positive rate on flagged accounts (blessing and a curse)

**Comment by samonthenetuk** [comment]
I am having a problem similar to this. When I am scanning quests and have levels 20-29 in the instances for some reason it just sits there and will not scan quests. If I change this to 20-20 it then starts scanning them again.
