### ISSUE TITLE
[Feature Request] Scan counter on scanning instances

### ISSUE THREAD

**Issue by SkOODaT** [RealDeviceMap/RealDeviceMap#66]
Would be nice if we had a counter to tell us how many scans each device is doing on raid or Pokemon scanning, ive included a quick example screenshot ...

![Udaddntitled](https://user-images.githubusercontent.com/8633932/79603550-92991600-80ba-11ea-9ac8-59f1e6c7972b.png)

**Comment by 123FLO321** [comment]
how many scans?
Total points in instance?
