### ISSUE TITLE
README should link to the Wiki

### ISSUE THREAD

**Issue by yw2theorycrafter** [RealDeviceMap/RealDeviceMap#7]
Many come to this github, see the README in its bare state with a link to vote on features, and assume there's no tutorial to install.

There is, in fact, it's just in the wiki.

Most people don't click on the wiki because, in my experience, most projects just don't use it and for most projects all the useful stuff is in the README.

It's the opposite case for this project. Can we link from the README to the Wiki? It'll reduce questions on the discord.

**Comment by JSzaszvari** [comment]
As this is an open source project you can always submit a pull request.

I've done this here - https://github.com/123FLO321/RealDeviceMap/pull/8
