### ISSUE TITLE
[Feature Request] Have the possibility to start multiple Assignments at once

### ISSUE THREAD

**Issue by Petap0w** [RealDeviceMap/RealDeviceMap#75]
**Is your feature request related to a problem? Please describe.**
At the moment auto-assignments are all separate, and for example in case of quest re-roll starting a scan on different areas is long.. Or switching to a different scan configuration during CDays for example.

**Describe the solution you'd like**
Possibility to have Assignment Groups where different assignments for different devices can be started all at once with one click.

**Describe alternatives you've considered**
Maybe have a checkbox in auto-assignment page to select multiple lines and "start all selected"

**Comment by jepke** [comment]
I guess what you want can be done by Device groups. Select X number of devices select instance and click safe all selected devices will move to the instance you picked.

**Comment by cks85** [comment]
> I guess what you want can be done by Device groups. Select X number of devices select instance and click safe all selected devices will move to the instance you picked.
No that's different, here is not about starting multiple devices on same task but multiple devices on different tasks at once.

**Comment by Dewpg** [comment]
Bump?

**Comment by Fabio1988** [comment]
done in #204
