### ISSUE TITLE
[Backend Bug Report] Leveling instance does not select new account

### ISSUE THREAD

**Issue by auisgold** [RealDeviceMap/RealDeviceMap#86]
**Describe the bug**
After the leveling instance has reached the max level a new account is not selected unless max account level is modified to a lower level. 

**To Reproduce**
1. Go to Instances page
2. Find a leveling instance
3. Wait for an account to reach max level
4. See the account has reached max level but a new account is not selected to continue leveling

**Expected behavior**
A new account should be selected for leveling once an account has reached max level. 

**System**
 - Running in docker: no
 - Docker Engine Version: [if applicable, e.g. 19.0]
 - Host OS: Ubuntu 16.04
 - RDM Version 1.6.13

**Comment by whitewillem** [comment]
max level 29 gets swapped out once its level 30.

**Comment by 123FLO321** [comment]
@auisgold max level should be 29 if you want to stop at 30.
Also just in case #83 adds a check for min/max level
