### ISSUE TITLE
[Backend Bug Report] Quest instance not finished on-complete triggered and device moved to new instance.

### ISSUE THREAD

**Issue by jepke** [RealDeviceMap/RealDeviceMap#95]
**Describe the bug**

**To Reproduce**
Quest instance is pretty big with remote rural areas. But quests not scanned change everyday either downtown where hundreds are in range. The next day it might actually be a remote few.

**Expected behavior**

Complete quests instance 100%

**Screenshots**
![image](https://user-images.githubusercontent.com/10245876/80891837-a20c8780-8c94-11ea-94c3-bba63a4fc472.png)

**System**
 - Running in docker: yes
 - Docker Engine Version: [if applicable, e.g. 19.0]
 - Host OS: [e.g. Ubuntu 18.04] 
 - RDM Version [e.g. 2.0.0]

**Additional context**

**Comment by jepke** [comment]
`[2020-05-02 15:56:08 GMT-05:00] [DEBUG] no job left (Got result: ["status": ok, "data": {
[2020-05-02 15:56:08 GMT-05:00] }]`

![image](https://user-images.githubusercontent.com/10245876/80892050-27446c00-8c96-11ea-8dc8-245abdea82d2.png)

**Comment by 123FLO321** [comment]
Are the stops closed?

**Comment by tppkgo** [comment]
Same experience here, large area never finishes. Stops are not closed. Reassigning a device back does not work.
`
Done: 16112\|16125/16125 (99.9\|100.0%)
--
`

**Comment by 123FLO321** [comment]
@jepke @tppkgo are those stops closed at night?

**Comment by jepke** [comment]
The ones in my screenshot actually are i found out later but in this same run i had other small clusters and single stops that had been skipped as well and those are not closed night time.
But as you mentioned on discord it might be the 3 mis skip function causing this. As most of the time the ones not being done are in rural areas.

**Comment by jepke** [comment]
Just had 1 tiny instance 371 stops stuck at 361 (route 100%) changed login delay to 86400 and it finished the last 10 in a minute after changing. Don't know if the instance edit triggered something or the login delay.

**Comment by 123FLO321** [comment]
Potentially fixed in #122 
Re-open if this is still an issue.
