### ISSUE TITLE
[Feature Request] Default number of Instances to show

### ISSUE THREAD

**Issue by drfsupercenter** [RealDeviceMap/RealDeviceMap#97]
**Is your feature request related to a problem? Please describe.**
I have slightly more than 25 instances, and after waiting for the page to load I have to keep tabbing over to the next page just to see the remaining few.  There is a dropdown for showing 25, 50, 100 or All, but nowhere to set what you would like that default number to be.

**Describe the solution you'd like**
An option in general settings to change the default number of values loaded on such pages as Instances, Devices, Auto-Assignments and such.

**Describe alternatives you've considered**
Not really relevant here

**Additional context**
Should be pretty obvious what I'm asking for.  There's obviously something hard-coded to set that default to 25 and it would be nice if we could change it to 50, 100 or All.

**Comment by cks85** [comment]
Having more than 100 instances I support that request to be able to set default page size from settings (for instances but devices and auto-assignments as well)
